//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courses.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoursesEntities : DbContext
    {
        public CoursesEntities()
            : base("name=CoursesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<CoursePoosition> CoursePoosition { get; set; }
        public virtual DbSet<CourseProfessionalField> CourseProfessionalField { get; set; }
        public virtual DbSet<CourseSkill> CourseSkill { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<FormOfEducation> FormOfEducation { get; set; }
        public virtual DbSet<LevelOfEducation> LevelOfEducation { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<ProfessionalField> ProfessionalField { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
    }
}
