//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSkill
    {
        public int CourseSkillID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> SkillID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Course Course1 { get; set; }
        public virtual Skills Skills { get; set; }
        public virtual Skills Skills1 { get; set; }
    }
}
