//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseProfessionalField
    {
        public int CourseProfessionalFieldID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> ProfessinalFieldID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Course Course1 { get; set; }
        public virtual ProfessionalField ProfessionalField { get; set; }
        public virtual ProfessionalField ProfessionalField1 { get; set; }
    }
}
